import { Inter, Luckiest_Guy, Quicksand } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });
const lucky = Luckiest_Guy({ subsets: ["latin"], weight: "400" });
const quick = Quicksand({ subsets: ["latin"] });

export const metadata = {
  title: "Innovatia 2.0 | Deparment Of M.Tech Computer Science And Engineering",
  description: "Generated by create next app",
};

//test commit

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="./rocket-cursor.png"
          type="image/x-icon"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true' />
        <link
          href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&display=swap"
          rel="stylesheet"
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,200;0,8..60,300;0,8..60,400;0,8..60,500;0,8..60,600;0,8..60,700;0,8..60,800;0,8..60,900;1,8..60,200;1,8..60,300;1,8..60,400;1,8..60,500;1,8..60,600;1,8..60,700;1,8..60,800;1,8..60,900&display=swap"
          rel="stylesheet"
        ></link>
        <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"></link>
      </head>
      <body className={`${quick.className}`}>
        <Sidebar />
        <main id="app" className="main-body bg-fixed bg-cover bg-no-repeat z-0">
          {children}
        </main>
      </body>
    </html>
  );
}
