import { Inter, Luckiest_Guy, Quicksand } from "next/font/google";
import "./globals.css";
import CustomCursor from "@/components/cursor";

const inter = Inter({ subsets: ["latin"] });
const lucky = Luckiest_Guy({ subsets: ["latin"], weight: "400" });
const quick = Quicksand({ subsets: ["latin"] });

export const metadata = {
  title: "Innovatia 2.0 | Deparment Of M.Tech Computer Science And Engineering",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <link
          rel='shortcut icon'
          href='./rocket-cursor.png'
          type='image/x-icon'
        />
      </head>
      <body
        className={`${lucky.className} bg-[url("/retro-bg-future.webp")] bg-fixed bg-cover bg-no-repeat`}>
        {children}
        <span className="hidden lg:block">
          <CustomCursor />
        </span>
      </body>
    </html>
  );
}
